spring:
  application:
    name: sprintboot-init


myname: "this is my name"
useforhaha: "this is for haha"
useforhello: "this is for hello"

address:
  - shanghai
  - beijing

name: "this is <<name>>"

person:
  name: "this is <<person.name>>"
  age: 22

